### ISSUE TITLE
Why use more LayerNorm in ImageEmbedding?

### ISSUE THREAD

**Issue by haowang1992** [ChenRocks/UNITER#19]
https://github.com/ChenRocks/UNITER/blob/feda6bb902085dbba198e201b791a7adba4c5ea2/model/model.py#L252

From the paper, I think there only one layernorm in the last step, but I notice there are more layernorms.

**Comment by ChenRocks** [comment]
Thanks for pointing this out. Some detailed implementation is omitted in the paper due to space limit/readability. Please follow this code base otherwise the pretrained checkpoint won't we correctly loaded.

In my opinion, a small difference of a single layer normalization layers wouldn't affect results much. If you have your own implementation w/o this layernorm and observe a significant drop, feel free to let me know. I will update the arXiv paper accordingly to make this clearer.
